### ISSUE TITLE
IMUPackage does not give access to a variety of information

### ISSUE THREAD

**Issue by careway** [luxonis/depthai-shared#135]
Hi everyone, 

I spotted this in the code: While trying to understand how to get access to the different types of information the IMUSensor was capable to bring. IMUPackage has Raw and any kind of processed fields commented out.

https://github.com/luxonis/depthai-shared/blob/32b30ef42cbe32137e3274031a049c401c46a2c1/include/depthai-shared/datatype/RawIMUData.hpp#L182-L207

Which makes it impossible to access any kind of raw data, gravity, etc ...

**Comment by szabi-luxonis** [comment]
They are unified, gravity, linear acceleration etc. are accesed through accelerometer data since they are a type of acceleration. 
See our examples provided in depthai core or python for raw sensors.

**Comment by careway** [comment]
Understood
