### ISSUE TITLE
Naming conflicts in serialization code

### ISSUE THREAD

**Issue by kota-rr** [luxonis/depthai-shared#45]
`struct IMUReportRotationVectorWAcc` has a member variable `accuracy` with the same name as its base class `IMUReport` which can cause unexpected serialization.

https://github.com/luxonis/depthai-shared/blob/main/include/depthai-shared/datatype/RawIMUData.hpp#L78

**Comment by Luxonis-Brandon** [comment]
Thanks for the report!  CC: @szabi-luxonis
